# Docker compose command
# sudo docker compose up -d
# docker exec -it <container_id|container_name> /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P <your_password>
# docker exec -u 0 <container_id|container_name> bash -c "chown mssql /var/opt/mssql"

# Using sqldev as sa password for development only
version: '3.7'

services:

# MongoDB server
  mongodb_datahome:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SQLdev2019!
      MSSQL_PID: Developer
      MSSQL_BACKUP_DIR: /var/opt/mssql/backup
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_LOG_DIR: /var/opt/mssql/log
    volumes:
      - ./mssql-volume:/var/opt/mssql
